### PR TITLE
Jellyfin webhook integration

### LINKED ISSUE #130: Jellyfin integration
A jellyfin integration via webhooks/plugin is planned so that episodes can be added automatically.

### PR DESCRIPTION
**Pull request by FuzzyGrim**
It seems that jellyfin incorrectly tracks the number of plays for each media (https://github.com/jellyfin/jellyfin-plugin-trakt/issues/226). Therefore, the integration will not handle rewatches for now.

### CODE REVIEW

**Comment by Radieserlbrot** [comment]
Hello @all,
am I right Yamtrack can now be linked to Jellyfin? How do I do this? Where can I find it in the settings? Sorry, I am a little newish to this topic. I just waited for the ability to connect both and have just installed Yamtrack a few minutes ago... Thanks for your help
Best

**Comment by FuzzyGrim** [comment]
It is currently in the dev branch, it will be merged in a couple of days. But you can test it if you want with the dev tag:

```
image: ghcr.io/fuzzygrim/yamtrack:dev
```

**Comment by FuzzyGrim** [comment]
@Radieserlbrot

Hey, I just released the new version with this feature :)

**Comment by Radieserlbrot** [comment]
> @Radieserlbrot
> 
> Hey, I just released the new version with this feature :)

Hi, thanks. Will try it out asap

**Pull request merged**
